# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=256)),
                ('verb', models.CharField(default='GET', max_length=32)),
                ('action', models.CharField(blank=True, choices=[('flat', 'Respond with Flat Response'), ('wsdl_replaced', 'Respond with cached find/replaced WSDL file')], default='', max_length=64)),
                ('delay_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('flat_response', models.TextField(blank=True, null=True)),
                ('master_wsdl_url', models.URLField(blank=True, null=True)),
                ('wsdl_find', models.CharField(blank=True, default='', max_length=128)),
                ('wsdl_replace', models.CharField(blank=True, default='', max_length=128)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
        ),
    ]
