# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, default='', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='delay_ms',
            field=models.PositiveIntegerField(blank=True, help_text='The response will be delayed by this much time, useful for simulating slow connections or causing timeouts.', null=True),
        ),
        migrations.AddField(
            model_name='ruleresponse',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rules.Rule'),
        ),
    ]
