# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20171224_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='flat_response',
        ),
    ]
