# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_remove_rule_flat_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSubstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find', models.TextField()),
                ('replace', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='rules.Rule')),
            ],
        ),
    ]
