# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_rulesubstitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='master_wsdl_url',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='wsdl_find',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='wsdl_replace',
        ),
        migrations.AddField(
            model_name='rule',
            name='live_url',
            field=models.URLField(blank=True, help_text='Used if a live URL should be retrieved.', null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.CharField(blank=True, choices=[('flat', 'Respond with Configured Response (chooses randomly from active if multiple available)'), ('live', 'Retrieve live URL')], default='', max_length=64),
        ),
    ]
